import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import SidebarR from "@/components/sidebarR/SidebarR";
import SidebarL from "@/components/sidebarL/SidebarL";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body className={inter.className}>
        <Header />
        <div className="flex">
          <SidebarL />
          <div className="flex-grow bg-secondary-main">{children}</div>
          <SidebarR />
        </div>
      </body>
    </html>
  );
}
